package com.kuriata.dao.connection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class WrappedConnection implements AutoCloseable{
    private Connection connection;
    private boolean isInTransaction;


    public WrappedConnection(Connection connection) {
        this.connection = connection;
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        connection.setAutoCommit(autoCommit);
        isInTransaction = !autoCommit;
    }

    public void setTransactionIsolation(int transactionIsolation) throws SQLException {
        connection.setTransactionIsolation(transactionIsolation);
    }

    public void commit() throws SQLException {
        connection.commit();
        isInTransaction = false;
    }

    public void rollback() throws SQLException {
        connection.rollback();
        isInTransaction = false;
    }

    public void close() throws SQLException {
        if (!isInTransaction) {
            connection.close();
        }
    }

    public PreparedStatement createStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    public Statement createStatement() throws SQLException {
        return connection.createStatement();
    }

    public boolean isClosed() throws SQLException {
        return connection.isClosed();
    }

}
